version: '3.7'
networks:
  perf:
    driver: bridge  # 指定网络驱动程序为bridge
services:
  postgresql:
    image: postgres:14.5
    container_name: postgresql    # 容器名为'postgresql'
    # 重启策略
    restart: always               # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    # 设置环境变量,相当于docker run命令中的-e
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      ALLOW_IP_RANGE: 0.0.0.0/0 # 允许所有ip访问
    # 数据卷挂载路径设置,将本机目录映射到容器目录
    volumes:
      - "./docker/postgresql/data:/var/lib/postgresql/data"
    # 映射端口
    ports:
      - "5432:5432"
    networks:
      - perf
  frontend:
    image: nginx:1.21.3
    container_name: frontend
    # 重启策略
    restart: always
    # 数据卷挂载路径设置,将本机目录映射到容器目录
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d"
      - "./frontend/my-vue-app/dist:/usr/share/nginx/html"
    # 映射端口
    ports:
      - "5000:80"
    networks:
      - perf
   backend:
    container_name: backend
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    # 重启策略
    restart: always
    # 映射端口
    ports:
      - "8000:8000"
    networks:
      - perf